import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
const SUPABASE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "";

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.warn(
    "[ChatBot DB] Supabase URL or Anon Key not set — chat history will not be persisted."
  );
}

export const supabase = createClient(
  SUPABASE_URL || "https://placeholder.supabase.co",
  SUPABASE_KEY || "placeholder-key"
);

/* ── Supabase Schema required for this chatbot ──
 *
 * Run this SQL in your Supabase SQL Editor:
 *
 * CREATE TABLE sessions (
 *   session_id UUID PRIMARY KEY,
 *   created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
 *   updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
 * );
 *
 * CREATE TABLE messages (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   session_id UUID REFERENCES sessions(session_id),
 *   role TEXT NOT NULL,
 *   content TEXT NOT NULL,
 *   timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
 * );
 *
 * -- Optional RLS settings if you aren't using anon key directly from the client.
 * -- Make sure to enable RLS or set policies according to your needs.
 */
